### ISSUE TITLE
PAGE correction to curations for PMID:16311336

### ISSUE THREAD

**Issue by Snowotarski** [planosphere/PAGE#1]
# Planarian Anatomy Gene Expression Observations (PAGE curations)

To be sure your curations are accepted, familiarize yourself with  with our [curation rules](https://github.com/planosphere/PAGE/blob/master/curation_rules.md).

# Curations are all for this one PMID:
add the pubmed id of your observations

# Are curations for a new publication or additions or corrections for existing curations?
[ ] New Publication 
[ X] Additions to exiting curations from a publication
[] Corrections to exiting curations

This issue does not require the table. Please change all (3) PLANA Term label records associated with PMID: 16311336 from neoblast to 'parenchyma' PLANA:0002142. This change is based on the authors word use. 

# Your Orcid
0000-0003-2569-1939

**Comment by srobb1** [comment]
@ejrsimr Since this is the curator correcting their own curations passed on wording in the publication, I think we should consider editing the original curation file and rerunning the format pipeline. What do you think?

**Comment by Snowotarski** [comment]
@srobb1  and @ejrsimr : to be clear, this is not a full re-annotation. These annotations are in ADDITION to the ones already present in PAGE.

**Comment by srobb1** [comment]
changes have been made and will be loaded into the db soon

**Comment by srobb1** [comment]
done
