### ISSUE TITLE
BUG: PAGE Curator ORCID

### ISSUE THREAD

**Issue by EudaldPascual** [planosphere/PAGE#10]
**Describe the bug**
My ORCID is not validated in the PAGE_annotator. 

My current ORCID is 0000-0002-9577-840X, but after introducing it at the curator request, it is not validated. It appears "Invalid Curator ID".

**To Reproduce**
1. Go to https://sanchezalvarado.shinyapps.io/PAGE_annotator/
2. Type 0000-0002-9577-840X at the curator request.
3. See error

**Expected behavior**
My ORCID should be validated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10 Enterprise]
 - Browser [chrome]
 - Version [95.0.4638.54]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by srobb1** [comment]
This bug has been corrected in this [commit](https://github.com/planosphere/PAGE/commit/fffea9d9ae86727f38d71bc3cf7d1ee1a5ab72d2). 

The annotator is up and running with these corrections.
