### ISSUE TITLE
Additional PAGE curations for 24737865

### ISSUE THREAD

**Issue by Snowotarski** [planosphere/PAGE#2]
# Planarian Anatomy Gene Expression Observations (PAGE curations)

To be sure your curations are accepted, familiarize yourself with our [curation rules](https://github.com/planosphere/PAGE/blob/master/curation_rules.md).

# Curations are all for this one PMID:
24737865

# Are curations for a new publication or additions or corrections for existing curations?
[ ] New Publication 
[x ] Additions to exiting curations from a publication
[ ] Corrections to exiting curations

Curator note: These were missed on the first round of annotation as the probe list was not included in the publication. This edit we have added the Genbank IDs for commonly used markers missed on the first pass. However, this citation is still missing a piece of expression evidence for collagen as there are 19 (as per Cote et al 2019 :https://www.nature.com/articles/s41467-019-09539-6) and we cannot be sure. Thus it is currently omitted. 

# Your Orcid
0000-0003-2569-1939
Orcid are required. Add your Orcid here. If you don't have one, get one [here](https://orcid.org/register).

# Add your curations  
[Download this Excel Sheet](https://github.com/planosphere/PAGE/raw/master/curation/PAGE_curation_table.xlsx), enter your curations, and copy and paste your resulting table below. Paste whole sheet or just the table of observations. If you only have a few curations you can just fill in values in table provided below.

If you are using the excel sheet, please save and retain for future questions we may have.

<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:////Users/stn/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel="File-List" href="file:////Users/stn/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>

<meta charset="utf-8">
<meta charset="utf-8">
<meta charset="utf-8">

PLANA   TERM ID (PLANA:0000429) | PLANA TERM   LABEL (neoblast) | Published   transcript ID | Specimen Type | Life Cycle Type | Experimental   Evidence Type
-- | -- | -- | -- | -- | --
PLANA:0000016 | pharynx | DN293829 | whole organism | asexual adult | colorimetric in situ   hybridization evidence
PLANA:0000026 | intestine | EU130791.1 | whole organism | asexual adult | colorimetric in situ   hybridization evidence
PLANA:0000016 | pharynx | BK007036.1 | whole organism | asexual adult | colorimetric in situ   hybridization evidence
PLANA:0000099 | neuron | JX010560.1 | whole organism | asexual adult | colorimetric in situ   hybridization evidence
PLANA:0000099 | neuron | BK007043 | whole organism | asexual adult | colorimetric in situ   hybridization evidence

[24737865_additions_PAGE_curation_table (5).xlsx](https://github.com/planosphere/PAGE/files/6592638/24737865_additions_PAGE_curation_table.5.xlsx)

# Select from these

## Specimen Types 

| Label | ID |  
| --- | ---|   
| FACS sorted cell population	 | PLANA: 0002138 |   
| whole organism | PLANA:0000136 |   

## Life Cycle Types 

| Label | ID |  
| --- | ---|   
| asexual adult	| PLANA:0004504 |  
| adult hermaphrodite | PLANA:0004503 |  
| stage 1| PLANA:0000001 |  
| stage 2| PLANA:0000002 |  
| stage 3| PLANA:0000003 |  
| stage 4| PLANA:0000004 |  
| stage 5| PLANA:0000005 |  
| stage 6| PLANA:0000006 |  
| stage 7| PLANA:0000007|  
| stage 8| PLANA:0000008 |  

## Experimental Evidence Types 

| Label | ID |  
| --- | ---| 
| single-cell RNA-sequencing evidence	| ECO:0001560 |   
| RNA-sequencing evidence	| ECO:0000295 |   
| fluorescence in situ hybridization evidence | ECO:0001047 |   
| colorimetric in situ hybridization evidence	| ECO:0001839 |  
| cDNA to DNA expression microarray evidence	| ECO:0000097 |

**Comment by srobb1** [comment]
@ejrsimr In order to make adding expression observations more accessible to everyone, we added this form to create observations. I need to write a parser to get this data into an appropriate format for your pipeline.

**Comment by srobb1** [comment]
We are changing the way we accept curations. We are now using a shiny app. See #3

**Comment by srobb1** [comment]
@Snowotarski Can you check the publications search results for this pub 24737865? We have some curations associated with an obsolete term

I added the new curations, they look good.

The older ones are the ones I think we need to fix. Do we delete or do we correct the term id for the obsolete terms?

![Screen Shot 2021-06-18 at 9 18 40 AM](https://user-images.githubusercontent.com/1072991/122583214-38754700-d016-11eb-8281-a3a57f549107.png)

**Comment by srobb1** [comment]
added curations
